title: 서영훈의 블로그
email: darktemi90@nate.com
description: >- 
  비트 캠프 NAVER CLOUD AIaaS 과정 1기 과정 수정중
baseurl: "" 
url: "https://github.com/darktemi"
twitter_username: 
github_username: darktemi

# Build settings
theme: minima
plugins:
  - jekyll-feed

